p8105_hw2_zx2527
================
Zihan Xiong
2025-09-28

## Problem 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(janitor)
```

    ## 
    ## Attaching package: 'janitor'
    ## 
    ## The following objects are masked from 'package:stats':
    ## 
    ##     chisq.test, fisher.test

1.  clean the data in file **pols-month.csv**

``` r
pols_month_df=read_csv(file="./data/pols-month.csv", na=c("NA","",".")) |>
janitor::clean_names() |>
  separate(mon,into = c("year","month","day"),sep = "-") |>

mutate(
    year=as.integer(year),
    month=as.integer(month),
    month=factor(
      month,
      levels = 1:12,
      labels = month.name
    ),
    president = case_match(
      prez_gop,
      1 ~ "gop",
      0 ~ "dem"
)
) |>
   select(-prez_gop, -prez_dem, -day) |>
   arrange(year,month)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

**Final table of pols_month**

``` r
pols_month_df
```

    ## # A tibble: 822 × 9
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <fct>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 January        23      51     253      23      45     198 dem      
    ##  2  1947 February       23      51     253      23      45     198 dem      
    ##  3  1947 March          23      51     253      23      45     198 dem      
    ##  4  1947 April          23      51     253      23      45     198 dem      
    ##  5  1947 May            23      51     253      23      45     198 dem      
    ##  6  1947 June           23      51     253      23      45     198 dem      
    ##  7  1947 July           23      51     253      23      45     198 dem      
    ##  8  1947 August         23      51     253      23      45     198 dem      
    ##  9  1947 September      23      51     253      23      45     198 dem      
    ## 10  1947 October        23      51     253      23      45     198 dem      
    ## # ℹ 812 more rows

2.  clean the data in file **snp.csv**

``` r
snp_df=read_csv(file="./data/snp.csv",na=c("NA","",".")) |>
  janitor::clean_names() |>
separate (date,into = c("month","day","year"),sep="/") |>
  mutate(
    year=as.integer(year),
    year=ifelse(year < 50, year + 2000, year + 1900),
    month=as.integer(month),
    day=as.integer(day),
    month=factor(
      month,
      levels=1:12,
      labels = month.name
    )) |>
  relocate(year,month) |>
  select( -day) |>
   arrange(year,month)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

**Final table of snp**

``` r
snp_df
```

    ## # A tibble: 787 × 3
    ##     year month     close
    ##    <dbl> <fct>     <dbl>
    ##  1  1950 January    17.0
    ##  2  1950 February   17.2
    ##  3  1950 March      17.3
    ##  4  1950 April      18.0
    ##  5  1950 May        18.8
    ##  6  1950 June       17.7
    ##  7  1950 July       17.8
    ##  8  1950 August     18.4
    ##  9  1950 September  19.5
    ## 10  1950 October    19.5
    ## # ℹ 777 more rows

3.  clean the data in file **unemployment.csv**

``` r
unemp_df=read_csv(file = "./data/unemployment.csv",na=c("NA","",".")) |>
  janitor::clean_names() |>
  pivot_longer(
  jan:dec,
  names_to = "month",
  values_to = "unemployment"
) |>
  mutate(
    year = as.integer(year),
    month = str_to_title(month),
    month = factor(
      month,
      levels = month.abb,
      labels = month.name
    )
  ) |>
arrange(year,month)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

**Final table of umemployment**

``` r
unemp_df
```

    ## # A tibble: 816 × 3
    ##     year month     unemployment
    ##    <int> <fct>            <dbl>
    ##  1  1948 January            3.4
    ##  2  1948 February           3.8
    ##  3  1948 March              4  
    ##  4  1948 April              3.9
    ##  5  1948 May                3.5
    ##  6  1948 June               3.6
    ##  7  1948 July               3.6
    ##  8  1948 August             3.9
    ##  9  1948 September          3.8
    ## 10  1948 October            3.7
    ## # ℹ 806 more rows

**merge the datasets**

``` r
merged_df=left_join(pols_month_df, snp_df, by=c("year","month"))
merged_final_df=left_join(merged_df,unemp_df, by=c("year","month"))
```

**Final merged table**

``` r
merged_final_df
```

    ## # A tibble: 822 × 11
    ##     year month   gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <dbl> <fct>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1  1947 January      23      51     253      23      45     198 dem          NA
    ##  2  1947 Februa…      23      51     253      23      45     198 dem          NA
    ##  3  1947 March        23      51     253      23      45     198 dem          NA
    ##  4  1947 April        23      51     253      23      45     198 dem          NA
    ##  5  1947 May          23      51     253      23      45     198 dem          NA
    ##  6  1947 June         23      51     253      23      45     198 dem          NA
    ##  7  1947 July         23      51     253      23      45     198 dem          NA
    ##  8  1947 August       23      51     253      23      45     198 dem          NA
    ##  9  1947 Septem…      23      51     253      23      45     198 dem          NA
    ## 10  1947 October      23      51     253      23      45     198 dem          NA
    ## # ℹ 812 more rows
    ## # ℹ 1 more variable: unemployment <dbl>

**Note**: Since close information in snp.csv started recording from
1950, and the unemployment information in unemployment.csv started
recording from 1948, so there are some **NAs** in the final table.

**Description of the datasets**

-The **pols-month** dataset records the number of national **politicians
(presidents, senators, representatives, governors)** by political party
in the United States, ranging from **1947 to 2015**.

-The **snp** dataset contains the monthly closing values of the **S&P
stock index**, covering the period from **1950 to 2015**.

-The **unemployment** dataset reports the **monthly unemployment** rate
in the U.S., spanning **1948 to 2015**, originally stored in wide format
and reshaped to long format for consistency.

After cleaning and merging these three datasets by year and month, the
resulting dataset contains approximately **822 rows and 12 columns**,
with key variables including year, month, president, counts of
governors/senators/representatives by party, the S&P closing value
(close), and the unemployment rate (unemployment). This unified dataset
facilitates analyses linking political context, economic performance,
and labor market conditions across nearly seven decades of U.S. history.

## Problem 2

``` r
library(readxl)
library(dplyr)
library(janitor)
```

1.  **To clean and organize**

``` r
clean_trash_sheet = function(sheet_name, wheel_label) {
  df = read_excel("./data/202409 Trash Wheel Collection Data.xlsx",
                  sheet = sheet_name,
                  skip = 1) |>
    clean_names() |>
    filter(!is.na(dumpster)) |>      
    select(dumpster:homes_powered) |> 
    mutate(
      year = as.integer(year),
      trash_wheel = wheel_label
    )
  
  if ("sports_balls" %in% names(df)) {
    df = df |> mutate(sports_balls = as.integer(round(sports_balls)))
  } else {
    df = df |> mutate(sports_balls = NA_integer_)
  }
  
  return(df)
}
```

2.  **combine**

``` r
mr_df = clean_trash_sheet("Mr. Trash Wheel", "Mr.")
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
prof_df = clean_trash_sheet("Professor Trash Wheel", "Professor")
gwynnda_df = clean_trash_sheet("Gwynnda Trash Wheel", "Gwynnda")

trash_df = bind_rows(mr_df, prof_df, gwynnda_df)
```

3.  **Final table**

``` r
trash_df
```

    ## # A tibble: 1,033 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,023 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

**Description**

The combined Trash Wheel dataset includes **1033** observations and
**15** variables, with each row representing the contents of a single
dumpster collected by one of Baltimore’s trash wheels.

Key variables include `year`, `month`, `weight_tons` (tons of trash
collected), `volume_cubic_yards`, and item-specific counts such as
`plastic_bottles`,`ploystyrene`, `cigarette_butts`, and `glass_bottles`.
An additional variable `trash_wheel` identifies whether the record
corresponds to Mr. Trash Wheel, Professsor Trash Wheel, or Gwynnda.

From the available data, Professor Trash Wheel has collected a total of
246.74 tons of trash since its deployment. Gwynnda collected 1.812^{4}
cigarette butts in June 2022. These data provide a tidy and consistent
summary of trash collection activities across multiple devices,
facilitating comparison of waste removal efforts over time and across
locations.

## Problem 3

``` r
library(tidyverse)
library(janitor)
```

1.  **import and clean zip_zori.csv**

``` r
zori_df = read_csv("./data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = starts_with("x"),     
    names_to = "date",
    values_to = "zori"
  ) |> 
  mutate(
    date = str_remove(date, "x"),        
    date = str_replace_all(date, "_", "-")  
  ) |> 
  separate(date, into = c("year", "month", "day"), sep = "-", remove = TRUE) |> 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    zip_code=as.character(region_name)
  ) |> 
  select(zip_code,year,month,zori) |>
  arrange(zip_code, year, month)
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

**Final table for Zillow**

``` r
zori_df
```

    ## # A tibble: 17,284 × 4
    ##    zip_code  year month  zori
    ##    <chr>    <int> <int> <dbl>
    ##  1 10001     2015     1 3855.
    ##  2 10001     2015     2 3892.
    ##  3 10001     2015     3 3898.
    ##  4 10001     2015     4 3970.
    ##  5 10001     2015     5 4033.
    ##  6 10001     2015     6 4071.
    ##  7 10001     2015     7 4067.
    ##  8 10001     2015     8 4070.
    ##  9 10001     2015     9 4040.
    ## 10 10001     2015    10 4023.
    ## # ℹ 17,274 more rows

2.  **import and clean zip code.csv**

``` r
zipcodes_df = read_csv("./data/Zip Codes.csv") |> 
  janitor::clean_names() |> 
  select(zip_code, county, neighborhood) |> 
  mutate(zip_code = as.character(zip_code))
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

**Final table for zip code**

``` r
zipcodes_df
```

    ## # A tibble: 322 × 3
    ##    zip_code county neighborhood              
    ##    <chr>    <chr>  <chr>                     
    ##  1 10451    Bronx  High Bridge and Morrisania
    ##  2 10452    Bronx  High Bridge and Morrisania
    ##  3 10453    Bronx  Central Bronx             
    ##  4 10454    Bronx  Hunts Point and Mott Haven
    ##  5 10455    Bronx  Hunts Point and Mott Haven
    ##  6 10456    Bronx  High Bridge and Morrisania
    ##  7 10457    Bronx  Central Bronx             
    ##  8 10458    Bronx  Bronx Park and Fordham    
    ##  9 10459    Bronx  Hunts Point and Mott Haven
    ## 10 10460    Bronx  Central Bronx             
    ## # ℹ 312 more rows

3.  **tidy**

``` r
final_df = left_join(zori_df, zipcodes_df, by = "zip_code")
```

    ## Warning in left_join(zori_df, zipcodes_df, by = "zip_code"): Detected an unexpected many-to-many relationship between `x` and `y`.
    ## ℹ Row 7541 of `x` matches multiple rows in `y`.
    ## ℹ Row 79 of `y` matches multiple rows in `x`.
    ## ℹ If a many-to-many relationship is expected, set `relationship =
    ##   "many-to-many"` to silence this warning.

**Description**

After cleaning and merging the datasets, the resulting tidy dataset
contains 17516 observations.  
There are 149 unique ZIP codes and 43 unique neighborhoods represented.

Key variables include:  
- **zip_code**: the postal code identifying geographic areas within
NYC  
- **borough**: the borough (county) corresponding to the ZIP code  
- **neighborhood**: finer spatial divisions nested within boroughs  
- **date / year / month**: temporal information for tracking rent trends
over time  
- **zori**: Zillow Observed Rent Index (ZORI), the standardized rental
price measure

This dataset allows us to analyze rental price trends across space (ZIP
codes, neighborhoods, boroughs) and time (2015–2024).

5.  **zip codes appear in the ZIP code dataset but not in the Zillow**

``` r
missing_zips = anti_join(zipcodes_df, zori_df, by = "zip_code")

missing_zips %>% 
  select(zip_code, county, neighborhood) %>% 
  head(10)
```

    ## # A tibble: 10 × 3
    ##    zip_code county neighborhood              
    ##    <chr>    <chr>  <chr>                     
    ##  1 10464    Bronx  Southeast Bronx           
    ##  2 10474    Bronx  Hunts Point and Mott Haven
    ##  3 10475    Bronx  Northeast Bronx           
    ##  4 10499    Bronx  <NA>                      
    ##  5 10550    Bronx  <NA>                      
    ##  6 10704    Bronx  <NA>                      
    ##  7 10705    Bronx  <NA>                      
    ##  8 10803    Bronx  <NA>                      
    ##  9 11202    Kings  <NA>                      
    ## 10 11224    Kings  Southern Brooklyn

**Description**

There are 171 ZIP codes present in the ZIP code dataset but not in the
Zillow rental dataset.  
For example, 10464 (Southeast Bronx, Bronx) and 10474 (Hunts Point and
Mott Haven, Bronx) are missing.

ZIP codes may be excluded for several reasons:  
- They may correspond to **non-residential areas** (e.g., parks,
airports, or industrial zones).  
- Some ZIP codes may cover **very small residential populations** with
insufficient rental data.  
- Others may represent **PO boxes or special-purpose ZIP codes**, which
do not have meaningful rent information.  
6. **Prices pre&post-COVID19 (2020 vs 2021)**

``` r
covid_comp = final_df %>%
  filter((year == 2020 & month == 1) | (year == 2021 & month == 1)) %>%
  select(zip_code, county, neighborhood, year, month, zori) %>%
  pivot_wider(
    names_from = year,
    values_from = zori,
    names_prefix = "zori_"
  ) %>%
  mutate(drop = zori_2021 - zori_2020) %>%
  arrange(drop) 

largest_drops = covid_comp %>%
  slice(1:10)
```

**first 10s table**

``` r
largest_drops
```

    ## # A tibble: 10 × 7
    ##    zip_code county   neighborhood                month zori_2020 zori_2021  drop
    ##    <chr>    <chr>    <chr>                       <int>     <dbl>     <dbl> <dbl>
    ##  1 10007    New York Lower Manhattan                 1     6334.     5422. -913.
    ##  2 10069    New York <NA>                            1     4623.     3875. -748.
    ##  3 10009    New York Lower East Side                 1     3406.     2692. -714.
    ##  4 10016    New York Gramercy Park and Murray H…     1     3731.     3019. -712.
    ##  5 10001    New York Chelsea and Clinton             1     4108.     3398. -710.
    ##  6 10002    New York Lower East Side                 1     3645.     2935. -710.
    ##  7 10004    New York Lower Manhattan                 1     3150.     2444. -706.
    ##  8 10038    New York Lower Manhattan                 1     3573.     2876. -698.
    ##  9 10012    New York Greenwich Village and Soho      1     3629.     2942. -686.
    ## 10 10010    New York Gramercy Park and Murray H…     1     3697.     3012. -685.

**Description** Rental prices showed dramatic declines during the
COVID-19 pandemic.  
Comparing January 2021 to January 2020, the 10 ZIP codes with the
largest rent decreases are shown in the table above.  
For instance, ZIP code 10007 in Lower Manhattan (New York) experienced a
decline of about -912.6 points on the ZORI scale.

These declines were concentrated in neighborhoods of Manhattan and parts
of Brooklyn, reflecting patterns where demand for rentals decreased
sharply due to remote work, migration out of the city, and
pandemic-related disruptions.
